'use client';

import { useCallback, useEffect, useState } from 'react';
import { KeyRound, RefreshCw } from 'lucide-react';
import { api, ApiError } from '@/lib/api';
import type { CatalogResponse, SavedConnection } from '@/types/api';

export default function DatabaseBrowserContent(){const [connections,setConnections]=useState<SavedConnection[]>([]);const [selected,setSelected]=useState('');const [catalog,setCatalog]=useState<CatalogResponse|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const loadConnections=useCallback(async()=>{try{const list=await api.listConnections();setConnections(list);if(list[0])setSelected(v=>v||list[0].id)}catch(e){setError(e instanceof ApiError?e.message:'Could not load connections')}},[]);useEffect(()=>{void loadConnections()},[loadConnections]);
 const load=useCallback(async()=>{if(!selected)return;setLoading(true);try{setCatalog(await api.connectionSchema(selected));setError('')}catch(e){setError(e instanceof ApiError?e.message:'Could not load schema')}finally{setLoading(false)}},[selected]);useEffect(()=>{void load()},[load]);
 async function refresh(){if(!selected)return;setLoading(true);try{setCatalog(await api.refreshSchema(selected));setError('')}catch(e){setError(e instanceof ApiError?e.message:'Refresh failed')}finally{setLoading(false)}}
 return <div className="h-full overflow-auto bg-slate-50 p-8 text-slate-900"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><h1 className="text-3xl font-bold">Schema Explorer</h1><p className="mt-2 text-sm text-slate-600">Live API data from the latest encrypted connection snapshot.</p></div><div className="flex gap-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded border bg-white p-2 text-sm"><option value="">Select connection</option>{connections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={refresh} disabled={!selected||loading} className="flex items-center gap-2 rounded bg-blue-600 px-3 py-2 text-sm text-white disabled:opacity-50"><RefreshCw className="h-4 w-4"/>Refresh</button></div></div>
 {error&&<div role="alert" className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}{loading?<p className="mt-8 text-sm text-slate-500">Introspecting schema…</p>:!catalog?<p className="mt-8 rounded border border-dashed bg-white p-8 text-center text-sm text-slate-500">Create and select a connection first.</p>:<div className="mt-6 space-y-6">{catalog.metadata.schemas.map(schema=><section key={schema.name}><h2 className="mb-3 text-lg font-semibold">{schema.name}</h2><div className="grid gap-4 lg:grid-cols-2">{schema.objects.map(obj=><article key={obj.name} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><h3 className="font-mono font-semibold">{obj.name}</h3><span className="rounded bg-slate-100 px-2 py-1 text-xs uppercase">{obj.type}</span></div><div className="mt-3 divide-y">{obj.columns.map(col=><div key={col.name} className="flex justify-between py-2 text-sm"><span>{obj.primary_key.includes(col.name)&&<KeyRound className="mr-1 inline h-3 w-3 text-amber-500"/>}{col.name}</span><span className="font-mono text-xs text-slate-500">{col.type}{col.nullable?' · nullable':''}</span></div>)}</div>{obj.foreign_keys.length>0&&<div className="mt-3 text-xs text-slate-600">{obj.foreign_keys.map((fk,i)=><p key={i}>FK {fk.columns.join(', ')} → {fk.referred_schema}.{fk.referred_table}({fk.referred_columns.join(', ')})</p>)}</div>}</article>)}</div></section>)}</div>}</div></div>}
