'use client';

import { useCallback, useEffect, useState } from 'react';
import { Download, Play, Save, Sparkles } from 'lucide-react';
import { api, ApiError } from '@/lib/api';
import type { QueryDraft, QueryExecution, SavedConnection } from '@/types/api';

export default function SqlEditorContent(){const [connections,setConnections]=useState<SavedConnection[]>([]);const [connection,setConnection]=useState('');const [question,setQuestion]=useState('');const [draft,setDraft]=useState<QueryDraft|null>(null);const [result,setResult]=useState<QueryExecution|null>(null);const [busy,setBusy]=useState<'generate'|'execute'|'save'|''>('');const [error,setError]=useState('');
 const load=useCallback(async()=>{try{const list=await api.listConnections();setConnections(list);if(list[0])setConnection(list[0].id)}catch(e){setError(e instanceof ApiError?e.message:'Could not load connections')}},[]);useEffect(()=>{void load()},[load]);
 async function generate(){if(!connection||!question.trim())return;setBusy('generate');setError('');setResult(null);try{setDraft(await api.generateQuery(connection,question))}catch(e){setDraft(null);setError(e instanceof ApiError?e.message:'SQL generation failed')}finally{setBusy('')}}
 async function execute(){if(!draft)return;setBusy('execute');setError('');try{setResult(await api.executeDraft(draft.draft_id))}catch(e){setError(e instanceof ApiError?e.message:'Query execution failed')}finally{setBusy('')}}
 async function save(){if(!result)return;setBusy('save');try{await api.saveExecutedAsVerified(result.query_id);alert('Verified example saved.')}catch(e){setError(e instanceof ApiError?e.message:'Could not save verified example')}finally{setBusy('')}}
 function csv(){if(!result)return;const escape=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;const content=[result.columns.join(','),...result.rows.map(row=>result.columns.map(c=>escape(row[c])).join(','))].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'text/csv'}));link.download=`query-${result.query_id}.csv`;link.click();URL.revokeObjectURL(link.href)}
 return <div className="h-full overflow-auto bg-slate-50 p-8 text-slate-900"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold">AI Query Workspace</h1><p className="mt-2 text-sm text-slate-600">Generate SQL first, review it, then explicitly approve execution.</p>
 <div className="mt-6 rounded-xl border bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[260px_1fr_auto]"><select value={connection} onChange={e=>{setConnection(e.target.value);setDraft(null);setResult(null)}} className="rounded border p-2 text-sm"><option value="">Select connection</option>{connections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Which five customers spent the most?" className="rounded border p-2 text-sm"/><button onClick={generate} disabled={!connection||!question.trim()||!!busy} className="flex items-center gap-2 rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Sparkles className="h-4 w-4"/>{busy==='generate'?'Generating…':'Generate SQL'}</button></div></div>
 {error&&<div role="alert" className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 {draft&&<section className="mt-6 grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border bg-white shadow-sm"><div className="border-b px-4 py-3 font-semibold">Generated SQL</div><pre className="overflow-auto whitespace-pre-wrap p-4 font-mono text-sm">{draft.sql}</pre><div className="border-t p-4"><button onClick={execute} disabled={!!busy} className="flex items-center gap-2 rounded bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Play className="h-4 w-4"/>{busy==='execute'?'Running safely…':'Run query'}</button><p className="mt-2 text-xs text-slate-500">Approval runs this exact server-stored draft in a read-only transaction. Draft expires {new Date(draft.expires_at).toLocaleTimeString()}.</p></div></div><aside className="rounded-xl border bg-white p-4 shadow-sm"><h2 className="font-semibold">Explanation</h2><p className="mt-2 text-sm text-slate-600">{draft.explanation}</p><p className="mt-4 text-xs font-semibold uppercase text-slate-500">Confidence</p><p className="text-sm">{Math.round(draft.confidence*100)}%</p><p className="mt-4 text-xs font-semibold uppercase text-slate-500">Assumptions</p>{draft.assumptions.length?<ul className="mt-1 list-disc pl-5 text-sm text-amber-700">{draft.assumptions.map(a=><li key={a}>{a}</li>)}</ul>:<p className="text-sm text-slate-500">None reported</p>}</aside></section>}
 {result&&<section className="mt-6 rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-semibold">Query results</h2><p className="text-xs text-slate-500">{result.row_count} rows · {result.duration_ms}ms</p></div><div className="flex gap-2"><button onClick={csv} className="flex items-center gap-1 rounded border px-3 py-2 text-xs"><Download className="h-3 w-3"/>CSV</button><button onClick={save} disabled={!!busy} className="flex items-center gap-1 rounded border px-3 py-2 text-xs"><Save className="h-3 w-3"/>Save verified query</button></div></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{result.columns.map(c=><th key={c} className="px-4 py-3 text-left">{c}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i} className="border-t">{result.columns.map(c=><td key={c} className="px-4 py-3 font-mono text-xs">{String(row[c]??'null')}</td>)}</tr>)}</tbody></table></div></section>}
 </div></div>}
